
# Azure Pipeline that run basic continuous integration on a Terraform project
# Running Pipeline from Main Branch, Creating artifacts, Publishing the artifacts and create plan.out

#trigger: none # Disable CI triggers.

trigger:
 branches:
   include:
   - stage
   - Prod
   exclude:
   - dev
   - Pre-Prod
   - Stage-Master
   - Prod-Master
pool:
  vmImage: ubuntu-latest

variables:
  - group: 'Constants for Azure Build Sandbox'
  - group: 'Constants for Azure Build Prod'
  - name: "Storage_client_id"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}: 
      value: '$(Storage_client_id_Sandbox)'
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}: 
      value: '$(Storage_client_id_Production)'
  - name: "Storage_client_secret"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}: 
      value: '$(Storage_client_secret_Sandbox)'
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}: 
      value: '$(Storage_client_secret_Production)'
  - name: "environmentType"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}: 
      value: 'Sandbox'
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}: 
      value: 'Production'
  - name: "client_id"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: $(clientID_Sandbox)
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: $(clientID_Production)
  - name: "client_secret"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: $(clientSecret_Sandbox)
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: $(clientSecret_Production)
  - name: "tenant_id"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: $(tenant_id_Sandbox)
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: $(tenant_id_Production)
  - name: "subscription_id"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: $(subscription_id_Sandbox)
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: $(subscription_id_Production)
  - name: "sourcePolicy-YAML"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "$(sourcePolicyYAMLSandbox)"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "$(sourcePolicyYAMLProd)"
  - name: "sourceMGYAML"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "$(sourceMGYAMLSandbox)"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "$(sourceMGYAMLProd)"
  - name: "Storage"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "$(StorageSandbox)"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "$(StorageProd)"
  - name: "Container"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "$(ContainerSandbox)"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "$(ContainerProd)"
  - name: "RG"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "$(RGSandbox)"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "$(RGProd)"
  - name: "policyStateFile"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "$(PolicyStateFileSandbox)"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "$(PolicyStateFileProd)"
  - name: "MGRAStateFile"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "$(MGRAStateFileSandbox)"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "$(MGRAStateFileProd)"
  - name: "accessKey"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "$(accessKeySandbox)"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "$(accessKeyProd)"
  - name: "artifact"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "sandbox-artifact"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "prod-artifact"
  - name: "Storage_tenant_id"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "$(Storage_tenant_id_Sandbox)"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "$(Storage_tenant_id_prod)"
  - name: "rootMG"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stage') }}:
      value: "GEVernovaSandbox"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
      value: "Vernova"

stages:
  - stage: Build_Approval
    displayName: Build Approval
    jobs:
    - deployment: Policy_and_MG_Build
      displayName: Build Process
      environment: $(environmentType)
      strategy:
        runOnce:
          deploy:
            steps:
            - task: PowerShell@2
              displayName: "Microsoft Agent IP"
              continueOnError: false
              inputs:
                targetType: 'inline'
                script: |
                  $ip = Invoke-RestMethod http://ipinfo.io/json | Select -exp ip
                  Write-Host "ip is : $ip"
  
  - stage: Policy_Initiative_Deployement
    displayName: Deployement of Policy and Initiative 
    jobs:
    - job: ContinuousIntegrationJob
      displayName: Policy and Initiative Job
      steps:     
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              az login --service-principal -u $(Storage_client_id) -p $(Storage_client_secret) --tenant $(Storage_tenant_id)
              $ip = Invoke-RestMethod http://ipinfo.io/json | Select -exp ip
              Write-Host "ip is : $ip"
              az storage account network-rule add -g "$(RG)" --account-name "$(Storage)" --ip-address "$ip"
              Start-Sleep -Seconds 30
          displayName: 'Adding agent IP in storage account'
          continueOnError: false

        - task: TerraformCLI@0
          displayName: 'Terraform Init'
          continueOnError: false
          inputs:
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            commandOptions: '-backend=true -reconfigure -backend-config="storage_account_name=$(Storage)" -backend-config="container_name=$(Container)" -backend-config="key=$(policyStateFile)" -backend-config="access_key=$(accessKey)"'
            allowTelemetryCollection: true

        - task: TerraformCLI@0
          displayName: 'Terraform Validate'
          continueOnError: false
          inputs:
            command: 'validate'
            allowTelemetryCollection: true
            workingDirectory: '$(System.DefaultWorkingDirectory)'

        - task: TerraformCLI@0
          displayName: 'Terraform Plan'
          continueOnError: false
          inputs:
            command: 'plan'
            commandOptions: '-target="module.PolicyandInitiativeCreation" -var sourcePolicyYAML=$(sourcePolicy-YAML) -var subscriptionID=$(subscription_id) -var tenantID=$(tenant_id) -var clientID=$(client_id) -var clientSecret=$(client_secret) -var sourceMG-YAML=$(sourceMGYAML)'
            allowTelemetryCollection: true
            workingDirectory: '$(System.DefaultWorkingDirectory)'
        
        - task: ArchiveFiles@2
          displayName: 'Create Plan Artifact'
          continueOnError: false
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)'
            includeRootFolder: false
            archiveType: 'tar'
            tarCompression: 'gz'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-policy-$(artifact).tgz'
            replaceExistingArchive: true
        
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Plan Artifact'
          continueOnError: false
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: '$(Build.BuildId)-policy-$(artifact)-tfplan'
            publishLocation: 'Container'
        
        - task: TerraformCLI@0
          displayName: 'Publish Plan to plan.out'
          continueOnError: false
          inputs:
            command: 'plan'
            commandOptions: '-target="module.PolicyandInitiativeCreation" -var sourcePolicyYAML=$(sourcePolicy-YAML) -var subscriptionID=$(subscription_id) -var tenantID=$(tenant_id) -var clientID=$(client_id) -var clientSecret=$(client_secret) -var sourceMG-YAML=$(sourceMGYAML)'
            allowTelemetryCollection: true
            publishPlanResults: 'plan.out' 
        
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              az login --service-principal -u $(Storage_client_id) -p $(Storage_client_secret) --tenant $(Storage_tenant_id)
              $ip = Invoke-RestMethod http://ipinfo.io/json | Select -exp ip
              Write-Host "ip is : $ip"
              az storage account network-rule remove --resource-group "$(RG)" --account-name "$(Storage)" --ip-address "$ip"
              Start-Sleep -Seconds 30
          displayName: 'Removal of agent IP in storage account'
          condition: succeededOrFailed()

  - stage: MG_RA_Policy_INI_Assignments
    displayName: MG RA Policy and Initiative Assignment
    jobs:
    - job: ContinuousIntegrationJob
      displayName: MG RA Policy INI Assignmnet Job
      steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              az login --service-principal -u $(Storage_client_id) -p $(Storage_client_secret) --tenant $(Storage_tenant_id)
              $ip = Invoke-RestMethod http://ipinfo.io/json | Select -exp ip
              Write-Host "ip is : $ip"
              az storage account network-rule add -g "$(RG)" --account-name "$(Storage)" --ip-address "$ip"
              Start-Sleep -Seconds 30
          displayName: 'Adding agent IP in storage account'
          continueOnError: false

        - task: TerraformCLI@0
          displayName: 'Terraform Init'
          continueOnError: false
          inputs:
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            commandOptions: '-backend=true -reconfigure -backend-config="storage_account_name=$(Storage)" -backend-config="container_name=$(Container)" -backend-config="key=$(MGRAStateFile)" -backend-config="access_key=$(accessKey)"'
            allowTelemetryCollection: true

        - task: TerraformCLI@0
          displayName: 'Terraform Validate'
          continueOnError: false
          inputs:
            command: 'validate'
            allowTelemetryCollection: true
            workingDirectory: '$(System.DefaultWorkingDirectory)'

        - task: TerraformCLI@0
          displayName: 'Terraform Plan'
          continueOnError: false
          inputs:
            command: 'plan'
            commandOptions: '-target="module.MG-RA-POL-INI-Assignment" -var sourcePolicyYAML=$(sourcePolicy-YAML) -var subscriptionID=$(subscription_id) -var tenantID=$(tenant_id) -var clientID=$(client_id) -var clientSecret=$(client_secret) -var sourceMG-YAML=$(sourceMGYAML) -var tenantrootMG=$(rootMG)'
            allowTelemetryCollection: true
            workingDirectory: '$(System.DefaultWorkingDirectory)'
        
        - task: ArchiveFiles@2
          displayName: 'Create Plan Artifact'
          continueOnError: false
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)'
            includeRootFolder: false
            archiveType: 'tar'
            tarCompression: 'gz'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-MG-$(artifact).tgz'
            replaceExistingArchive: true
        
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Plan Artifact'
          continueOnError: false
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: '$(Build.BuildId)-MG-$(artifact)-tfplan'
            publishLocation: 'Container'
        
        - task: TerraformCLI@0
          displayName: 'Publish Plan to plan.out'
          continueOnError: false
          inputs:
            command: 'plan'
            commandOptions: '-target="module.MG-RA-POL-INI-Assignment" -var sourcePolicyYAML=$(sourcePolicy-YAML) -var subscriptionID=$(subscription_id) -var tenantID=$(tenant_id) -var clientID=$(client_id) -var clientSecret=$(client_secret) -var sourceMG-YAML=$(sourceMGYAML) -var tenantrootMG=$(rootMG)'
            allowTelemetryCollection: true
            publishPlanResults: 'plan.out' 

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              az login --service-principal -u $(Storage_client_id) -p $(Storage_client_secret) --tenant $(Storage_tenant_id)
              $ip = Invoke-RestMethod http://ipinfo.io/json | Select -exp ip
              Write-Host "ip is : $ip"
              az storage account network-rule remove --resource-group "$(RG)" --account-name "$(Storage)" --ip-address "$ip"
              Start-Sleep -Seconds 30
          displayName: 'Removal of agent IP in storage account'
          condition: succeededOrFailed()